server {
    listen 80;
    listen [::]:80;

    server_name beautyhelper.ru www.beautyhelper.ru;

    root /var/www/beautyhelper;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
