"""initial

Revision ID: 08de60d68ca7
Revises: 
Create Date: 2026-05-28 22:10:28.623245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08de60d68ca7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='ID пакета'),
    sa.Column('title', sa.String(length=1024), nullable=False, comment='Название пакета'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание'),
    sa.Column('spins_count', sa.Integer(), nullable=False, comment='Количество генераций в пакете'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False, comment='Цена (руб)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активен ли пакет'),
    sa.Column('for_sale', sa.Boolean(), nullable=False, comment='Доступен ли для продажи'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата последнего обновления'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='ID продукта'),
    sa.Column('link_ga', sa.String(length=2083), nullable=False, comment='Уникальная ссылка на карточку товара в Золотом Яблоке'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Название продукта'),
    sa.Column('article_ga', sa.String(length=100), nullable=False, comment='Артикул в Золотом Яблоке'),
    sa.Column('product_type', sa.String(length=255), nullable=False, comment='Тип продукта (сокращённо)'),
    sa.Column('product_type_detailed', sa.String(length=255), nullable=False, comment='Тип продукта подробно'),
    sa.Column('purpose', sa.String(length=255), nullable=True, comment='Назначение'),
    sa.Column('hair_type', sa.String(length=255), nullable=True, comment='Тип волос'),
    sa.Column('skin_type', sa.String(length=255), nullable=True, comment='Тип кожи'),
    sa.Column('application_area', sa.String(length=255), nullable=True, comment='Область применения'),
    sa.Column('target_audience', sa.String(length=255), nullable=True, comment='Для кого'),
    sa.Column('ingredients', sa.Text(), nullable=True, comment='Состав (полный текст)'),
    sa.Column('ingredients_list', sa.JSON(), nullable=True, comment='Элементы состава списком'),
    sa.Column('ingredients_count', sa.Integer(), nullable=True, comment='Количество элементов состава'),
    sa.Column('measure_type', sa.String(length=20), nullable=False, comment='Мера (объём или количество)'),
    sa.Column('measure_value', sa.Numeric(precision=10, scale=2), nullable=True, comment='Количество меры'),
    sa.Column('measure_unit', sa.String(length=20), nullable=False, comment='Юниты меры (мл или шт)'),
    sa.Column('price_rub', sa.Numeric(precision=10, scale=2), nullable=False, comment='Стоимость (руб)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание'),
    sa.Column('usage', sa.Text(), nullable=True, comment='Применение'),
    sa.Column('brand', sa.String(length=255), nullable=False, comment='Бренд'),
    sa.Column('brand_country', sa.Text(), nullable=True, comment='Страна бренда'),
    sa.Column('brand_description', sa.Text(), nullable=True, comment='Описание бренда'),
    sa.Column('additional_info', sa.Text(), nullable=True, comment='Дополнительная информация'),
    sa.Column('image_link', sa.String(length=2083), nullable=True, comment='Ссылка на изображение в облаке ЗЯ'),
    sa.Column('image_key', sa.String(length=255), nullable=True, comment='Ключ изображения на S3'),
    sa.Column('characteristics', sa.Text(), nullable=True, comment='Характеристики'),
    sa.Column('fill_status', sa.Enum('EMPTY', 'IN_PROGRESS', 'DONE', 'FAILED', name='product_fill_status'), nullable=False, comment='Статус заполнения данных'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата последнего обновления'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link_ga')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Внутренний ID пользователя'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email — основной идентификатор для входа'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='Хеш пароля'),
    sa.Column('username', sa.String(length=150), nullable=True, comment='Отображаемое имя (опционально)'),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True, comment='ID пользователя в Telegram (привязка позже)'),
    sa.Column('language_code', sa.String(length=10), nullable=True, comment='Код языка (ru, en и т.д.)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активен ли аккаунт'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='Суперпользователь'),
    sa.Column('is_banned', sa.Boolean(), nullable=False, comment='Заблокирован ли пользователь'),
    sa.Column('email_confirmed', sa.Boolean(), nullable=False, comment='Подтверждён ли email'),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True, comment='Последний вход'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата последнего обновления'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telegram_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('balance_operations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='ID операции'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='ID пользователя'),
    sa.Column('type_operation', sa.Enum('ADD', 'RESERVE', 'CONFIRM', 'RELEASE', 'MANUAL', name='balance_operation_type'), nullable=False, comment='Тип операции'),
    sa.Column('count', sa.Integer(), nullable=False, comment='Количество генераций'),
    sa.Column('description', sa.Text(), nullable=True, comment='Комментарий к операции'),
    sa.Column('balance_after', sa.Integer(), nullable=False, comment='Баланс после операции'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата последнего обновления'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('selections',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='ID подборки'),
    sa.Column('product_id', sa.BigInteger(), nullable=False, comment='ID продукта, по которому сделана подборка'),
    sa.Column('task_type', sa.Enum('COMPOSITION_ANALYSIS', 'BEST_CHOICE', 'ANALOG', name='selection_task_type'), nullable=False, comment='Тип задачи подборки'),
    sa.Column('selection_status', sa.Enum('QUEUE', 'PROCESS', 'DONE', 'FAILED', name='selection_status'), nullable=False, comment='Статус генерации подборки'),
    sa.Column('pdf_url', sa.String(length=2083), nullable=True, comment='Ссылка на PDF-файл подборки'),
    sa.Column('request_details', sa.Text(), nullable=True, comment='Отправленные данные в OpenAI для анализа'),
    sa.Column('final_analysis', sa.Text(), nullable=True, comment='Финальный ответ от OpenAI'),
    sa.Column('price', sa.JSON(), nullable=True, comment='Стоимость запроса к OpenAI'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Сообщение об ошибке'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата последнего обновления'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_balances',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='ID записи баланса'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='ID пользователя'),
    sa.Column('spins', sa.Integer(), nullable=False, comment='Доступные генерации'),
    sa.Column('reserved_spins', sa.Integer(), nullable=False, comment='Зарезервированные генерации'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата последнего обновления'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_packages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='ID записи'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='ID пользователя'),
    sa.Column('package_id', sa.BigInteger(), nullable=True, comment='ID пакета'),
    sa.Column('delivery_type', sa.Enum('PURCHASE', 'PROMO', 'MANUAL', name='user_package_delivery'), nullable=False, comment='Способ получения пакета'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата последнего обновления'),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('selection_users',
    sa.Column('selection_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['selection_id'], ['selections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('selection_id', 'user_id')
    )
    op.create_table('waitings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='ID ожидания'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='Пользователь который ожидает подборку'),
    sa.Column('selection_id', sa.BigInteger(), nullable=False, comment='Подборка за которой следим'),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='waiting_status'), nullable=False, comment='Текущий статус ожидания'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата последнего обновления'),
    sa.ForeignKeyConstraint(['selection_id'], ['selections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'selection_id', name='uq_waiting_user_selection')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('waitings')
    op.drop_table('selection_users')
    op.drop_table('user_packages')
    op.drop_table('user_balances')
    op.drop_table('selections')
    op.drop_table('balance_operations')
    op.drop_table('users')
    op.drop_table('products')
    op.drop_table('packages')
    # ### end Alembic commands ###
